@startuml
!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml
!include osaPuml/Hardware/all.puml
!include osaPuml/Misc/all.puml
!include osaPuml/Server/all.puml
!include osaPuml/Site/all.puml


osa_server(webserver,   "192.168.1.104", "Ubuntu Server 20.04 LTS", "Web Server")
osa_server(canarE,      "192.168.1.101", "Ubuntu Server 20.04 LTS", "CanarE")
osa_server(basestation, "192.168.1.102", "Ubuntu Server 20.04 LTS", "Base Station")
osa_desktop(pcapp,   "192.168.1.103", "Ubuntu Server 20.04 LTS", "PC App")
osa_server(storage,     "192.168.1.105", "Ubuntu Server 20.04 LTS", "Storage")

' Network

osa_cloud(cloud, "Internet", "Network")


together {
  canarE -> basestation
  basestation -> canarE
  basestation -> pcapp
}

pcapp -> basestation
pcapp -> webserver

webserver -> pcapp
pcapp -> storage

footer %filename() rendered with PlantUML version %version()\nThe Hitchhiker’s Guide to PlantUML
@enduml
