@startuml
Project starts 2022-08-29

[Design] lasts 15 days
[Test] lasts 10 days
[Test] starts at [Design]'s end

[Design] is colored in GreenYellow/Green
[Test] is colored in Fuchsia/Firebrick

[Design] is 20% completed
[Test] is 10% completed
@enduml
