@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include DEVICONS/java.puml
!include DEVICONS/postgresql.puml
!include DEVICONS/webplatform.puml
!include DEVICONS/sqllite.puml

!include DEVICONS2/dotnetcore.puml
!include DEVICONS2/embeddedc.puml
!include DEVICONS2/matlab.puml
!include DEVICONS2/rails.puml

!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml


Person(hpc, "Healthcare Provider", "People that treat Patients", $sprite="users")
Person(patient, "Person receiving Therapy", "People that have an implant or wearable", $sprite="users")


System_Boundary(c1, "YellowBird Medical Cloud", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {
  Container(server, "Therapy Server", "RAILs 6.1.6", "clinic-server-staging \n qa3.yellowmdicaltest.com \n App Service \n Dockerized \n Ubuntu 20.04 LTS", $sprite="rails")
  Container(worker, "Therapy Worker", "RAILs 6.1.6", "cm-clc-qa3-uws-clinic-worker-staging-01-func \n Function App \n Dockerized \n Ubuntu 20.04 LTS", $sprite="rails")
  Container(dist, "PC App Distribution Service", "Authorized users", "https://clinic-app-dist-staging.azurewebsites.net",$sprite="webplatform")
  ContainerDb(devdb, "Therapy Server", "PostgreSQL", "clinic-db-server.postgres.database.azure.com \n port: 5432 \n dbname: staging \n\n Users\nPatients\nTest Cases", $sprite="postgresql")
  ContainerDb(storagedb, "Therapy Server", "Azure Blob", "Raw CTE Data \n device2cloudfiles \n staging \n staging-log \n staging-failed \n staging-processed")
}

System_Boundary(c2, "Healthcare Provider", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {
  Container(pcapp, "Therapy App", "C#, UAP, 10.0.17763.0", "Edition Windows 10 Pro \n Version 21H1 \n OS Build 19043.1889 \n Pack 120.2212.4180.0", $sprite="dotnetcore")
  ContainerDb(localdb, "Database", "sqllite", "Holds ...", $sprite="sqllite")
}

System_Boundary(c3, "Patient", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {
  Container(bs, "Base station", "C/C++", "Operating Room, Physicians Office, or Home", $sprite="embeddedc")
  Container(implant, "Implant \n or Wearable", "C/C++", "Medical device providing Therapy readings", $sprite="embeddedc")
}

System_Boundary(c4, "YellowBird Cloud Data Management Platform", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {
  Container(cc, "Therapy Calc", "matlab", "clinic-calc-staging \n 172.18.0.5 \n Win10 Pro N", $sprite="matlab.md")
  ContainerDb(cdb, "Therapy Database", "PostgreSQL", "Holds ...", $sprite="postgresql")
  Container(cdmp, "CDMP", "Web App", "https://qa3.yellowmdicaltest.com", $sprite="webplatform")
  ContainerDb(cdmpdb, "cdmp", "PostgreSQL", "Holds ...", $sprite="postgresql")
}

Rel(hpc, pcapp, "Uses", "https")
Rel(hpc, bs, "Uses")
Rel(hpc, server, "Uses", "https, GraphQL")

Rel(bs, implant, "Connects")
Rel(implant, patient, "Connects", "WiFi")

Rel_L(pcapp, bs, "Connects", "USB ")
Rel(pcapp, localdb, "Records Temporary Threapy Readings")
Rel_R(pcapp, dist, "Downloads new Therapy PC App", "HTTP")
Rel_R(pcapp, storagedb, "Pushes Threapy Readings to Cloud Storage")

Rel(server, devdb, "Read/Write", "HTTP")

Rel(worker, storagedb, "CTE Data file Processor", "device2cloudfiles/stgtelemetrydatadev")
Rel(worker, devdb, "Read/Write", "HTTP")
Rel_R(worker, cdb, "Periodic Therapy Database Importer")
Rel(worker, cdmpdb, "Periodic CDMP Data Importer")

Rel(cdb, cc, "Provides")
Rel(cdmpdb, cdmp, "Provides")
@enduml
